### ISSUE TITLE
Замечания по FindIndex

### ISSUE THREAD

**Issue by sergey-shambir** [bogdanov-d-a/CppMetaprogramming#1]
- при вызове предиката через invoke стоит добавить perfect forwarding, см. также https://stackoverflow.com/questions/18543717/c-perfect-forwarding
- я бы предложил для наглядности добавить static_cast в size_t: `return -1;`
- здесь `const auto&` можно заменить на универсальную ссылку `auto&&`:
```
for (auto const& elem : range)
{
    // ...
```

**Comment by bogdanov-d-a** [comment]
Исправлено.
