### ISSUE TITLE
Замечания по MovableFunction

### ISSUE THREAD

**Issue by sergey-shambir** [bogdanov-d-a/CppMetaprogramming#2]
* в такой форме оператор вызова принимает параметры по значению, даже если в оригинале они передавались по `const&` или `&&`:
```cpp
template<typename ResultType, typename... ArgsType>
class Holder
{
public:
	virtual ~Holder() = default;
	virtual ResultType operator()(ArgsType...) const = 0;
};
```
См. как идею решения: https://stackoverflow.com/questions/37997318/perfect-forwarding-template-parameter-pack-to-emplace-back-failed-compilation

* Аналогично, не хватает perfect forwarding:

```
ResultType operator()(ArgsType... args) const final
{
	return m_function(args...);
}
```
* В конструкторе `MovableFunction(FunctionType && function)` предлагаю заменить `std::move` на `std::forward`, т.к. превращать `const&` в `&&`, например, нет нужды; см. также https://stackoverflow.com/questions/9671749/whats-the-difference-between-stdmove-and-stdforward

**Comment by bogdanov-d-a** [comment]
Исправлено.

**Comment by sergey-shambir** [comment]
OK
